baseurl = "http://www.thepdxtechguy.org/"
languageCode = "en-us"
paginate = 10
theme = "hugo-minimalist-theme"
title = "PDX Tech Guy | IT Friendship"
[params]
copyright = "Powered by [Hugo](http://gohugo.io)."
custom_css = []
custom_js = []
location = "Portland, OR"
site_author = "Guy Cutting"
site_description = "Friendly IT and consulting services"
[social]
behance = ""
dribbble = ""
facebook = ""
github = ""
gplus = ""
instagram = ""
linkedin = ""
twitter = ""
