baseurl = "http://www.thepdxtechguy.org/"
languageCode = "en-us"
title = "PDX Tech Guy | IT Friendship"
# Define how many pages appear per site
paginate = 10
# Enable gogle analytics by entering your tracking code
# googleAnalytics = ""
theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command
# themesDir = "../.."

[params]
    site_author = "Guy Cutting"
    site_description = "Friendly IT and consulting services"
    location = "Portland, OR"
    # Link custom assets relative to /static
    # avatar = "img/profile-image.png"
    # header_background = "img/desk.jpg"
    # header_title = "Customizable header title"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = ""
    gplus     = ""
